---
new_page_extension: html
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: heading
  label: PT
- type: document
  path: parceiros.html
  label: Parceiros
- type: document
  path: contactos.html
  label: Contactos
- type: document
  path: sobre.html
  label: Sobre
- type: document
  path: arquivo.html
  label: Arquivo
- type: document
  path: index.html
  label: Home
- type: directory
  path: _events
  label: Eventos
  create: documents
  match: "**/*"
  new_doc_ext: html
  templates:
  - event
- type: heading
  label: ENG
- type: directory
  path: _events_eng
  label: Events
  create: documents
  match: "**/*"
  new_doc_ext: ".html"
  templates:
  - event
upload_dir: assets/img
public_path: "/assets/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
